#!/usr/bin/env bash

# install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install packages
brew install \
  caskroom/cask/brew-cask \
  antigen \
  zsh \
  readline \
  python \
  python3 \
  macvim \
  vim \
  flac \
  hub \
  git \
  gnu-tar \
  grc \
  lame \
  wget \

